# Группа веб-серверов
[webservers]
web-1 ansible_host=111.88.254.243 fqdn=web-1.ru-central1.internal
web-2 ansible_host=111.88.241.31 fqdn=web-2.ru-central1.internal

# Группа баз данных
[databases]
main ansible_host=111.88.248.203 fqdn=main.ru-central1.internal
replica ansible_host=93.77.183.230 fqdn=replica.ru-central1.internal

# Группа storage
[storage]
storage ansible_host=62.84.125.133 fqdn=storage.ru-central1.internal