version: "3"

include:
  - path: ./proxy.yaml

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - /root/.env
x-restart: &restart
  restart: on-failure

services:

  web:
    image: cr.yandex/crpot1igreghat8sokkr/my-app:1.0.0
    networks:
      backend:
        ipv4_address: 172.20.0.5
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24